### ISSUE TITLE
Database Question

### ISSUE THREAD

**Issue by annarankin** [annarankin/up-for-grabs#1]
Hi Neel, good morning! I just started working on the Backbone part of my app, and I'm having some issues with async and when things are loading - particularly my item view's template. I know it's there, and I can select it, but I can't seem to get it to be there in my view.

**Comment by darthneel** [comment]
Want to meet on the 4th floor for a chat?

**Comment by annarankin** [comment]
Ok - just let me know when

**Comment by darthneel** [comment]
10 minutes!

**Comment by annarankin** [comment]
Ok! Zanks :)
